// <auto-generated />
using CoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreApp.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20210220005809_InitialDatabaseCreation")]
    partial class InitialDatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreApp.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssignmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            AssignmentId = 1,
                            AssignmentName = "Assignment 6.1",
                            GitHubUrl = "Test Url"
                        });
                });

            modelBuilder.Entity("CoreApp.Models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelId");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            Name = "Level1"
                        },
                        new
                        {
                            LevelId = 2,
                            Name = "Level2"
                        },
                        new
                        {
                            LevelId = 3,
                            Name = "Level3"
                        },
                        new
                        {
                            LevelId = 4,
                            Name = "Level4"
                        },
                        new
                        {
                            LevelId = 5,
                            Name = "Level5"
                        },
                        new
                        {
                            LevelId = 6,
                            Name = "Level6"
                        },
                        new
                        {
                            LevelId = 7,
                            Name = "Level7"
                        },
                        new
                        {
                            LevelId = 8,
                            Name = "Level8"
                        },
                        new
                        {
                            LevelId = 9,
                            Name = "Level9"
                        },
                        new
                        {
                            LevelId = 10,
                            Name = "Level10"
                        });
                });

            modelBuilder.Entity("CoreApp.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "John",
                            Grade = 92,
                            LastName = "Doe"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Sally",
                            Grade = 79,
                            LastName = "Johnson"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Jim",
                            Grade = 88,
                            LastName = "Fredrick"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Carrie",
                            Grade = 69,
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "Larry",
                            Grade = 96,
                            LastName = "Fisher"
                        },
                        new
                        {
                            StudentId = 6,
                            FirstName = "Fred",
                            Grade = 84,
                            LastName = "Doe"
                        },
                        new
                        {
                            StudentId = 7,
                            FirstName = "Kelly",
                            Grade = 76,
                            LastName = "Johnson"
                        },
                        new
                        {
                            StudentId = 8,
                            FirstName = "Wendy",
                            Grade = 91,
                            LastName = "Fredrick"
                        },
                        new
                        {
                            StudentId = 9,
                            FirstName = "Justin",
                            Grade = 72,
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentId = 10,
                            FirstName = "Peytyn",
                            Grade = 94,
                            LastName = "Fisher"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
